extent.reporter.spark.start=true
extent.reporter.spark.out=target/extent-report/AutomationExecutionReport.html

screenshot.dir=target/extent-report/screenshots
screenshot.rel.path=./screenshots

systeminfo.os=Windows 11
systeminfo.user=Aadil
systeminfo.project=M.Tech Continuous Testing Framework	
systeminfo.browser=Chrome